This is makeindex, version 2.15 [MiKTeX 2.9.7200] (kpathsea + Thai support).
Scanning style file ./memoria.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file memoria.acn....done (5 entries accepted, 0 rejected).
Sorting entries....done (14 comparisons).
Generating output file memoria.acr....done (18 lines written, 0 warnings).
Output written in memoria.acr.
Transcript written in memoria.alg.
